CREATE TABLE jsrcakhm.registro (id_usuario INT AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(255) NOT NULL,
ApellidoP VARCHAR(255) NOT NULL,
ApellidoM VARCHAR(255) NOT NULL,
Telefono INT NOT NULL,
Email VARCHAR(255) NOT NULL,
Contraseña VARCHAR(255)) ENGINE=INNODB; 